baseURL = "http://gotoaws.cloudguru.run/"
ignoreFiles = [ "\\.files/README.md$",  ]
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Intro To Analytics On AWS workshop"
theme = "hugo-theme-learn"
uglyurls = false
sectionPagesMenu = "main"
relativeURLs = true

[blackfriday]
  hrefTargetBlank = true

[params]
  editURL = "https://github.com/kynging/IntroToAnalyticsOnAWSWorkshopChinese"
  themeVariant = "mine"
  showVisitedLinks = false
  author = "AWS<fengbiao@amazon.com>"
  description = ""
  disableSearch = false
  disableAssetsBusting = false
  disableShortcutsTitle = true
  branch = "master"
  pygmentsUseClasses = true
  pygmentsCodeFences = true
  pygmentsCodefencesGuessSyntax = true
  pygmentsStyle = "tango"
  codeRepoName = "/IntroToAnalyticsOnAWSWorkshopChinese"


[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub Project"
url = "https://github.com/kynging/IntroToAnalyticsOnAWSWorkshopChinese"
weight = 30

[[menu.shortcuts]]
name = "<i class='fas fa-envelope'></i> Have questions?"
url = "https://github.com/kynging/IntroToAnalyticsOnAWSWorkshopChinese/issues"
weight = 40

[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]